// Generated by CoffeeScript 1.4.0
(function() {

  this.SlideSet = (function() {

    function SlideSet($slides) {
      if ($slides == null) {
        $slides = [];
      }
      this.slides = $slides;
      this.slide_count = this.slides.length;
      this.slides.attr('data-slide-state', 'hidden');
      this.current_slide = 0;
      this.prev_slide = 0;
      this.jump(this.current_slide);
    }

    SlideSet.prototype.queue = function(slide) {
      return this.slides.push(slide);
    };

    SlideSet.prototype.next = function() {
      return this.jump(this.current_slide + 1);
    };

    SlideSet.prototype.prev = function() {
      return this.jump(this.current_slide - 1);
    };

    SlideSet.prototype.jump = function(n) {
      if (n == null) {
        n = 0;
      }
      this.prev_slide = this.current_slide;
      this.current_slide = n;
      if (this.current_slide >= this.slide_count) {
        this.current_slide = 0;
      }
      if (this.current_slide < 0) {
        this.current_slide = this.slide_count - 1;
      }
      return this.transition_slides();
    };

    SlideSet.prototype.transition_slides = function() {
      $("[data-slide-state=previous]").attr('data-slide-state', 'hidden');
      this.slides[this.prev_slide].setAttribute('data-slide-state', 'previous');
      return this.slides[this.current_slide].setAttribute('data-slide-state', 'current');
    };

    return SlideSet;

  })();

}).call(this);
